import asyncio
import heapq
from wizwalker import XYZ, Orient, Client, Keycode
from wizwalker.file_readers.wad import Wad
import math
import struct
from io import BytesIO
from typing import Tuple, Union
from loguru import logger
from src.utils import is_free
from copy import copy

type_format_dict = {
"char": "<c",
"signed char": "<b",
"unsigned char": "<B",
"bool": "?",
"short": "<h",
"unsigned short": "<H",
"int": "<i",
"unsigned int": "<I",
"long": "<l",
"unsigned long": "<L",
"long long": "<q",
"unsigned long long": "<Q",
"float": "<f",
"double": "<d",
}



class TypedBytes(BytesIO):
    def split(self, index: int) -> Tuple["TypedBytes", "TypedBytes"]:
        self.seek(0)
        buffer = self.read(index)
        return type(self)(buffer), type(self)(self.read())
    def read_typed(self, type_name: str):
        type_format = type_format_dict[type_name]
        size = struct.calcsize(type_format)
        data = self.read(size)
        return struct.unpack(type_format, data)[0]



# implemented from https://github.com/PeechezNCreem/navwiz/
# this licence covers the below function
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

def parse_nav_data(file_data: Union[bytes, TypedBytes]):
    # ty starrfox for remaking this
    if isinstance(file_data, bytes):
        file_data = TypedBytes(file_data)
    vertex_count = file_data.read_typed("short")
    vertex_max = file_data.read_typed("short")
    # unknown bytes
    file_data.read_typed("short")
    vertices = []
    idx = 0
    while idx <= vertex_max - 1:
        x = file_data.read_typed("float")
        y = file_data.read_typed("float")
        z = file_data.read_typed("float")
        vertices.append(XYZ(x, y, z))
        vertex_index = file_data.read_typed("short")
        if vertex_index != idx:
            vertices.pop()
            vertex_max -= 1
        else:
            idx += 1
    edge_count = file_data.read_typed("int")
    edges = []
    for idx in range(edge_count):
        start = file_data.read_typed("short")
        stop = file_data.read_typed("short")
        edges.append((start, stop))
    return vertices, edges

def get_neighbors(vertex: XYZ, vertices: list[XYZ], edges: list[(int, int)]):
    vert_idx = -1
    for v in vertices:
        vert_idx += 1
        if v == vertex:
            break
    if vert_idx == -1:
        # no matching index found, return empty
        return []

    result = []
    for edge in edges:
        if edge[0] == vert_idx:
            result.append(vertices[edge[1]])
    return result


def build_nav_adjacency(vertices: list[XYZ], edges: list[tuple[int, int]]) -> dict[int, list[int]]:
    """Undirected adjacency list for the zone nav graph.

    Nav edges are stored one-way (``get_neighbors`` only follows ``edge[0]``), but the
    graph is physically traversable both ways, so we add both directions — otherwise
    A* connectivity is wrong and many vertices look unreachable.
    """
    n = len(vertices)
    adj: dict[int, list[int]] = {i: [] for i in range(n)}
    for a, b in edges:
        if 0 <= a < n and 0 <= b < n:
            adj[a].append(b)
            adj[b].append(a)
    return adj


def nearest_nav_vertex(vertices: list[XYZ], xyz: XYZ) -> int:
    """Index of the nav vertex closest (3D) to ``xyz``, or -1 if there are none."""
    best_i, best_d = -1, None
    for i, v in enumerate(vertices):
        d = calc_squareDistance(v, xyz)
        if best_d is None or d < best_d:
            best_d, best_i = d, i
    return best_i


def a_star_nav(vertices: list[XYZ], adj: dict[int, list[int]], start_i: int,
               goal_i: int, target_xyz: XYZ) -> int:
    """A* over the nav graph from ``start_i`` toward the target.

    Returns the index of the vertex to teleport to: ``goal_i`` (the vertex nearest the
    target) when it's reachable from the start, otherwise the *reachable* vertex closest
    to ``target_xyz``. We only need the destination vertex — the player teleports there
    directly rather than walking the path — so the heuristic just steers the search at
    the target and ``best_i`` tracks the closest vertex actually reached. Edge cost and
    heuristic are straight-line distance.
    """
    def h(i: int) -> float:
        return calc_Distance(vertices[i], target_xyz)

    open_heap = [(h(start_i), start_i)]
    g = {start_i: 0.0}
    best_i, best_h = start_i, h(start_i)
    visited: set[int] = set()
    while open_heap:
        _, cur = heapq.heappop(open_heap)
        if cur in visited:
            continue
        visited.add(cur)
        if h(cur) < best_h:
            best_h, best_i = h(cur), cur
        if cur == goal_i:
            return goal_i
        gc = g[cur]
        for nb in adj.get(cur, ()):
            ng = gc + calc_Distance(vertices[cur], vertices[nb])
            if nb not in g or ng < g[nb]:
                g[nb] = ng
                heapq.heappush(open_heap, (ng + h(nb), nb))
    return best_i


def calc_PointOn3DLine(xyz_1 : XYZ, xyz_2 : XYZ, additional_distance):
    # extends a point on the line created by 2 XYZs by additional_distance. xyz_1 is the origin.
    distance = calc_Distance(xyz_1, xyz_2)
    # distance = math.sqrt((pow(xyz_1.x - xyz_2.x, 2.0)) + (pow(xyz_1.y - xyz_2.y, 2.0)) + (pow(xyz_1.z - xyz_2.z, 2.0)))
    # Doing a rough distance check here since XYZ's aren't always equal even if they have seemingly the same values
    if distance < 1.0:
        return xyz_1
    else:
        n = ((distance - additional_distance) / distance)
        return XYZ(x=((xyz_2.x - xyz_1.x) * n) + xyz_1.x, y=((xyz_2.y - xyz_1.y) * n) + xyz_1.y, z=((xyz_2.z - xyz_1.z) * n) + xyz_1.z)


def are_xyzs_within_threshold(xyz_1 : XYZ, xyz_2 : XYZ, threshold : int = 200):
    # checks if 2 xyz's are within a rough distance threshold of each other. Not actual distance checking, but precision isn't needed for this, this exists to eliminate tiny variations in XYZ when being sent back from a failed port.
    threshold_check = [abs(abs(xyz_1.x) - abs(xyz_2.x)) < threshold, abs(abs(xyz_1.y) - abs(xyz_2.y)) < threshold, abs(abs(xyz_1.z) - abs(xyz_2.z)) < threshold]
    return all(threshold_check)


def calc_squareDistance(xyz_1 : XYZ, xyz_2 : XYZ):
    # calculates the distance between 2 XYZs, but doesn't square root the answer to be much more efficient. Useful for comparing distances, not much else.
    return (pow(xyz_1.x - xyz_2.x, 2.0)) + (pow(xyz_1.y - xyz_2.y, 2.0)) + (pow(xyz_1.z - xyz_2.z, 2.0))


def calc_Distance(xyz_1 : XYZ, xyz_2 : XYZ):
    # calculates the distance between 2 XYZs
    return math.sqrt(calc_squareDistance(xyz_1, xyz_2))


async def calc_FrontalVector(client: Client, xyz : XYZ = None, yaw : float = None, speed_constant : int = 580, speed_adjusted : bool = True, length_adjusted : bool = True):
    # handle if it is adjusted via speed multiplier or just uses the set constant
    if speed_adjusted:
        current_speed = await client.client_object.speed_multiplier()
    else:
        current_speed = 0

    # handles optional xyz param, will default to using the position of the client
    if not xyz:
        xyz = await client.body.position()

    # handles optional yaw paraam, will default to using the yaw of the client
    if not yaw:
        yaw = await client.body.yaw()
    else:
        yaw = yaw

    # adjust the speed constant based on the speed multiplier
    additional_distance = speed_constant * ((current_speed / 100) + 1)

    # calculate point "in front" of XYZ/client using yaw
    frontal_x = (xyz.x - (additional_distance * math.sin(yaw)))
    frontal_y = (xyz.y - (additional_distance * math.cos(yaw)))
    frontal_xyz = XYZ(x=frontal_x, y=frontal_y, z=xyz.z)

    # make a length adjustment since diagonal movements
    if length_adjusted:
        distance = calc_Distance(xyz, frontal_xyz)
        final_xyz = calc_PointOn3DLine(xyz_1=xyz, xyz_2=frontal_xyz, additional_distance=(additional_distance - distance))
    else:
        final_xyz = frontal_xyz

    return final_xyz


# TODO: This has 2 duplicates
async def load_wad(path: str):
    if path is not None:
        return Wad.from_game_data(path.replace("/", "-"))

async def teleport_move_adjust(client: Client, xyz : XYZ, delay : float = 0.7):
    # teleports the client to a given XYZ, and jitters afterward to actually update the position
    if await is_free(client):
        # print("teleport started")
        try:
            await client.teleport(xyz, wait_on_inuse= True, purge_on_after_unuser_fixer = True)
        except:
            pass
        # print("teleport completed")
        await asyncio.sleep(delay)
        await client.send_key(Keycode.A, 0.05)
        await client.send_key(Keycode.D, 0.05)
    else:
        print("not free didn't teleport_move_adjust")
        await asyncio.sleep(0.5)

def rotate_point(origin_xyz : XYZ, point_xyz : XYZ, theta):
    # rotates point_xyz about origin_xyz, by theta degrees counterclockwise. This doesn't take the Z into account, so don't use this for anything that needs the Z to rotate.
    radians = math.radians(theta)
    cos = math.cos(radians)
    sin = math.sin(radians)
    y_diff = point_xyz.y - origin_xyz.y
    x_diff = point_xyz.x - origin_xyz.x
    x = cos * x_diff - sin * y_diff + origin_xyz.x
    y = sin * x_diff + cos * y_diff + origin_xyz.y
    return XYZ(x=x, y=y, z=point_xyz.z)

async def auto_adjusting_teleport(client: Client, quest_position: XYZ = None):
    # DEPRECATED: Uses brute forcing XYZs in an alternating spiral pattern to find usable coords to port to. VERY slow.
    original_zone_name = await client.zone_name()
    original_position = await client.body.position()
    if not quest_position:
        quest_position = await client.quest_position.position()

    adjusted_position = quest_position
    mod_amount = 50
    current_angle = 0
    if await is_free(client):
        await teleport_move_adjust(client, quest_position)
    else:
        return
    while are_xyzs_within_threshold((await client.body.position()), original_position, 50) and await client.zone_name() == original_zone_name:
        if not await is_free(client):
                return
        elif not are_xyzs_within_threshold(original_position, quest_position, 1):
            adjusted_position = calc_PointOn3DLine(original_position, quest_position, mod_amount)
            rotated_position = rotate_point(quest_position, adjusted_position, current_angle)
            if await is_free(client):
                await teleport_move_adjust(client, rotated_position)
            else:
                return
            mod_amount += 100
            current_angle += 92
        else:
            break
            
async def fallback_spiral_tp(client: Client, xyz: XYZ):
    await auto_adjusting_teleport(client, xyz)

async def navmap_tp(client: Client, xyz: XYZ = None, leader_client: Client = None):
    # TODO: What is leader_client meant to be for?
    if not await is_free(client):
        return

    logger.debug(f"[navmap_tp] {client.title}: using navmap teleport (direct -> nav data -> spiral)")
    starting_zone = await client.zone_name() # for loading the correct wad and to walk to target as a last resort
    starting_xyz = await client.body.position()
    target_xyz = xyz if xyz is not None else await client.quest_position.position()

    def check_sigma(a: XYZ, b: XYZ, sigma=5.0):
        # check if a distance is more or less zero
        return calc_Distance(a, b) <= sigma

    async def check_success():
        # Check if the teleport succeeded. For this we want to have moved away from the starting position.
        await asyncio.sleep(1) # make sure we got useful information
        return not check_sigma(await client.body.position(), starting_xyz)

    async def finished_tp():
        return await check_success() or not await is_free(client) or await client.zone_name() != starting_zone

    if check_sigma(starting_xyz, target_xyz):
        return # save some work

    await client.teleport(target_xyz)
    if await finished_tp():
        return # trivial tp, no point using a more complex method if this one works

    try:
        # attempt to use the nav data
        wad = await load_wad(starting_zone)
        nav_file = await wad.get_file("zone.nav")
        vertices, edges = parse_nav_data(nav_file)
    except:
        # Unable to load nav data. Fall back to primitive spiral pattern
        await fallback_spiral_tp(client, target_xyz)
        return

    # continuation of nav data tp, don't want to swallow potential exceptions in this section
    closest_vertex = vertices[0]
    lowest_distance = calc_Distance(closest_vertex, target_xyz)
    for i in range(1, len(vertices)):
        vertex = vertices[i]
        vert_dist = calc_Distance(vertex, target_xyz)
        if vert_dist < lowest_distance:
            closest_vertex = vertex
            lowest_distance = vert_dist

    max_depth = 3
    queue = [[closest_vertex]]
    relevant = set()
    while len(queue) > 0:
        path = queue.pop()
        v = path[-1]
        relevant.add(v)
        for neighbor in get_neighbors(v, vertices, edges):
            if neighbor in relevant or len(path) + 1 > max_depth:
                continue
            new_path = list(path)
            new_path.append(neighbor)
            queue.append(new_path)

    # average position of the vertices
    avg_xyz = XYZ(0, 0, 0)
    for v in relevant:
        avg_xyz.x += v.x
        avg_xyz.y += v.y
        avg_xyz.z += v.z
    avg_xyz = XYZ(avg_xyz.x / len(relevant), avg_xyz.y / len(relevant), avg_xyz.z / len(relevant))
    # vector from average xyz to target
    av = XYZ(target_xyz.x - avg_xyz.x, target_xyz.y - avg_xyz.y, avg_xyz.z - target_xyz.z)
    # midpoint of line from average point to target
    ap2 = XYZ(avg_xyz.x + av.x / 2, avg_xyz.y + av.y / 2, avg_xyz.z + av.z / 2)
    await client.teleport(ap2)
    if await check_success():
        if await is_free(client) and await client.zone_name() == starting_zone:
            await client.goto(target_xyz.x, target_xyz.y)
        return
    await client.teleport(avg_xyz) # average point
    if await check_success():
        if await is_free(client) and await client.zone_name() == starting_zone:
            await client.goto(target_xyz.x, target_xyz.y)
        return
    await fallback_spiral_tp(client, target_xyz)


# The player's wall-clearance radius, clamped to a small collision-capsule range.
# The model footprint (and half-height) reflect the *visual* extent — staff, cape,
# nameplate — which is several times the body's real collision radius. Using that
# large value as wall clearance erodes narrow walkable corridors and throws the
# teleport far past the target, so we clamp it to a sane capsule size.
_PLAYER_RADIUS_MIN = 25.0
_PLAYER_RADIUS_MAX = 55.0


async def _resolve_player_radius(client: Client, zone_name: str) -> float:
    """Horizontal wall-clearance radius of the player's body, in world units.

    Pulls the player object's footprint radius (scaled by body scale) when it
    resolves, else the vertical half-height proxy, then a constant — and clamps the
    result to ``[_PLAYER_RADIUS_MIN, _PLAYER_RADIUS_MAX]`` so an over-large visual
    footprint can't make the collision solve overshoot.
    """
    try:
        scale = await client.body.scale()
    except Exception:
        scale = 1.0
    radius = None
    try:
        from src import entity_collision

        tid = await client.client_object.template_id_full()
        r = await asyncio.to_thread(
            entity_collision.get_object_collider_radius, tid, zone_name
        )
        if r and r > 0:
            radius = r * scale
    except Exception:
        radius = None
    if radius is None:
        try:
            radius = (await client.body.height()) * scale * 0.5
        except Exception:
            radius = 45.0
    return max(_PLAYER_RADIUS_MIN, min(radius, _PLAYER_RADIUS_MAX))


# Retreat offsets (world units) from a blocked destination back toward the approach
# anchor, tried in order until a teleport sticks. The collision solver only knows the
# *modeled* geometry (collision.bcd walls + gamedata.bin solid colliders); warp /
# teleporter trigger volumes (e.g. AZ-TELEPORT-…) carry no solid-collision file yet
# still rubber-band you, so a geometrically-clear landing can be rejected. When that
# happens we step back along the approach line until we're clear of the object.
_RETREAT_STEPS = (70.0, 140.0, 230.0, 350.0, 520.0)


async def _arrived(client: Client, dest: XYZ, settle: float = 1.0, tol: float = 60.0) -> bool:
    """True if, after letting the server settle, we actually landed near ``dest``.

    Compares only the horizontal plane — a rubber-band off a collider throws you far
    in x/y, while ``z`` always terrain-snaps and would otherwise cause false misses.
    Unreadable position -> assume success (don't thrash on a transient read error).
    """
    await asyncio.sleep(settle)
    try:
        pos = await client.body.position()
    except Exception:
        return True
    return math.hypot(pos.x - dest.x, pos.y - dest.y) <= tol


async def teleport_collision_verified(client: Client, dest: XYZ, anchor: XYZ) -> bool:
    """Teleport to ``dest`` and confirm the server accepted it; on a rubber-band,
    retreat toward ``anchor`` in increasing steps until a landing sticks.

    The decisive collision teleport assumes the destination clears every obstacle,
    but unmodeled warp volumes still bounce you. We verify the landing and, if it
    bounced, back off along the line toward ``anchor`` (the player's start) — each
    retreat is itself verified, so one that clips a modeled wall just rolls to the
    next. Returns True once a teleport sticks, False if every attempt bounced
    (caller should fall back to navmap_tp).
    """
    if not await is_free(client):
        return False
    await client.teleport(dest)
    if await _arrived(client, dest):
        return True
    for back in _RETREAT_STEPS:
        point = calc_PointOn3DLine(anchor, dest, back)  # 'back' units from dest toward anchor
        if calc_Distance(point, dest) < 1.0:
            break  # anchor too close to retreat any further
        if not await is_free(client):
            return False
        logger.debug(
            f"[collision_tp] {client.title}: destination bounced; retreating {back:.0f}u "
            f"toward start -> {point}"
        )
        await client.teleport(point)
        if await _arrived(client, point):
            return True
    return False


async def collision_tp(client: Client, xyz: XYZ = None, leader_client: Client = None):
    """Teleport by solving the zone's collision geometry — a single, decisive teleport.

    Loads the zone collision data, computes (in a 2D slice at the target's height)
    the nearest point that lies on walkable mesh and clears every collision object,
    and teleports there exactly once. Because that point is geometrically guaranteed
    to be outside all walls, there's no trial-and-error: it's first-time-every-time.

    Only when the geometry can't be solved — no collision data for the zone, a target
    outside the loaded area of interest, or a solve/teleport error — does it fall back
    to the proven navmap_tp. Debug logs report exactly which path ran.
    """
    if not await is_free(client):
        return

    target_xyz = xyz if xyz is not None else await client.quest_position.position()
    starting_xyz = await client.body.position()
    if calc_Distance(starting_xyz, target_xyz) <= 5.0:
        return  # already there

    safe_xyz = None
    reason = "unavailable"
    try:
        # Imported lazily so shapely/numpy load only when collision TP is actually
        # used, and any import error degrades to navmap rather than breaking import.
        from src.collision import CollisionWorld, get_collision_data
        from src.collision_math import find_safe_collision_point
        from src import entity_collision

        zone_name = await client.zone_name()
        player_radius = await _resolve_player_radius(client, zone_name)

        collision_data = await get_collision_data(client, zone_name)
        world = CollisionWorld()
        world.load(collision_data)

        # Static entity colliders (NPCs, teleporters, props) aren't in collision.bcd —
        # they come from the zone's gamedata.bin object table. That's read from files for
        # the WHOLE zone, so colliders outside render range are known *before* we move,
        # which is what keeps this a single, first-time teleport. It's all file/CPU work
        # (cached per zone), so the entire solve runs off the event loop.
        def _solve():
            extra_shapes = entity_collision.build_zone_static_shapes(zone_name, target_xyz.z)
            return find_safe_collision_point(
                world, target_xyz, player_radius, extra_shapes=extra_shapes, zone_name=zone_name
            )

        safe_xyz, reason = await asyncio.to_thread(_solve)
    except Exception as e:
        logger.debug(f"[collision_tp] {client.title}: collision solve errored ({e!r}); using navmap TP")
        safe_xyz = None

    if safe_xyz is not None:
        moved = ((safe_xyz.x - target_xyz.x) ** 2 + (safe_xyz.y - target_xyz.y) ** 2) ** 0.5
        logger.debug(
            f"[collision_tp] {client.title}: collision TP ({reason}, r={player_radius:.0f}) -> "
            f"{safe_xyz} (moved {moved:.0f}u from target)"
        )
        if await teleport_collision_verified(client, safe_xyz, starting_xyz):
            return
        logger.debug(
            f"[collision_tp] {client.title}: collision point bounced (unmodeled collider); "
            f"falling back to navmap TP"
        )

    else:
        logger.debug(f"[collision_tp] {client.title}: no collision solution ({reason}); falling back to navmap TP")
    await navmap_tp(client, xyz, leader_client)


async def a_star_tp(client: Client, xyz: XYZ = None, leader_client: Client = None):
    """Pathfinding teleport: A* over the zone nav graph + collision-validated landing.

    Uses A* over ``zone.nav`` to find the nav vertex nearest the target that's actually
    *reachable* from where the player stands (connectivity, not geometric nearness — the
    closest vertex may sit across a wall). That vertex is only an anchor: because zone.nav
    can disagree with collision.bcd and place it inside a wall, the collision navmesh then
    snaps it onto walkable ground and marches toward the target, and we make one teleport
    to that validated-walkable point. So the landing is both *reachable* (A*) and *not in
    a wall* (collision navmesh).

    Falls back to ``navmap_tp`` (direct teleport -> nav heuristic -> spiral) when the zone
    ships no nav data, the graph is empty, or no walkable point can be validated.
    """
    if not await is_free(client):
        return

    target_xyz = xyz if xyz is not None else await client.quest_position.position()
    starting_xyz = await client.body.position()
    if calc_Distance(starting_xyz, target_xyz) <= 5.0:
        return  # already there

    starting_zone = await client.zone_name()
    try:
        wad = await load_wad(starting_zone)
        nav_file = await wad.get_file("zone.nav")
        vertices, edges = parse_nav_data(nav_file)
    except Exception:
        logger.debug(f"[a_star_tp] {client.title}: no nav data; falling back to navmap TP")
        await navmap_tp(client, xyz, leader_client)
        return

    if not vertices:
        logger.debug(f"[a_star_tp] {client.title}: empty nav graph; falling back to navmap TP")
        await navmap_tp(client, xyz, leader_client)
        return

    adj = build_nav_adjacency(vertices, edges)
    start_i = nearest_nav_vertex(vertices, starting_xyz)
    goal_i = nearest_nav_vertex(vertices, target_xyz)
    end_i = a_star_nav(vertices, adj, start_i, goal_i, target_xyz)
    end_vertex = vertices[end_i]
    reached_goal = end_i == goal_i

    # The A* vertex is only an *anchor* near the target. A* runs on zone.nav, which can
    # disagree with collision.bcd and place that vertex inside a wall — so we never trust
    # it directly. The collision navmesh snaps it onto walkable ground and marches toward
    # the target, returning the furthest *validated-walkable* point; we teleport once to
    # that. If no collision navmesh is available we can't vet the vertex, so we defer to
    # navmap rather than risk teleporting into a wall.
    destination = None
    try:
        from src.collision import CollisionWorld as _CW, get_collision_data as _gcd
        from src.collision_math import closest_walkable_along, find_safe_collision_point

        from src import entity_collision

        player_radius = await _resolve_player_radius(client, starting_zone)
        coll_data = await _gcd(client, starting_zone)
        cworld = _CW()
        cworld.load(coll_data)

        # Static entity colliders (NPCs, props, the UniverseTeleport) live in gamedata.bin,
        # not collision.bcd — fold them in so the march won't land us on top of one. Built
        # in the worker thread (file/CPU work, cached per zone).
        #
        # The A* march guarantees a *reachable* landing but, because the nav graph is sparse
        # and the march is a straight line, it can stop far short of the target (no vertex
        # near a dock end, a wall splitting the line). The geometric solve returns the point
        # *closest* to the target that's on walkable mesh and wall-clear. Both are valid
        # first-try landings, so we take whichever is nearer the target — a_star_tp is then
        # never worse than collision_tp at getting close, while still preferring the marched
        # point when it's the closer one.
        def _solve():
            extra_shapes = entity_collision.build_zone_static_shapes(starting_zone, target_xyz.z)
            marched = closest_walkable_along(
                cworld, starting_zone, end_vertex, target_xyz, player_radius, extra_shapes=extra_shapes
            )
            nearest, _reason = find_safe_collision_point(
                cworld, target_xyz, player_radius, extra_shapes=extra_shapes, zone_name=starting_zone
            )
            candidates = [c for c in (marched, nearest) if c is not None]
            if not candidates:
                return None
            return min(candidates, key=lambda c: calc_squareDistance(c, target_xyz))

        destination = await asyncio.to_thread(_solve)
    except Exception as e:
        logger.debug(f"[a_star_tp] {client.title}: walkable solve failed ({e!r})")

    if destination is None:
        logger.debug(f"[a_star_tp] {client.title}: no validated walkable point; falling back to navmap TP")
        await navmap_tp(client, xyz, leader_client)
        return

    logger.debug(
        f"[a_star_tp] {client.title}: A* vertex {end_i} "
        f"({'goal' if reached_goal else 'closest reachable'}) -> single teleport to "
        f"{destination} ({calc_Distance(destination, target_xyz):.0f}u from target)"
    )

    if await teleport_collision_verified(client, destination, starting_xyz):
        return
    logger.debug(
        f"[a_star_tp] {client.title}: destination bounced (unmodeled collider); "
        f"falling back to navmap TP"
    )
    await navmap_tp(client, xyz, leader_client)


async def find_walkable_magic_points(client: Client, factor: float, limit: int = 8) -> list[XYZ]:
    """Resolve up to ``limit`` walkable magic-grid points, **ranked nearest-first** —
    HiveMind's "teleport onto the magic grid", with fallbacks.

    Solves against the same zone collision geometry as ``collision_tp`` (so each
    grid point clears every modeled wall/static collider), restricted to magic-grid
    intersections. Returns a ranked shortlist so the caller can teleport to the
    closest, confirm it stuck, and drop to the next when the game rubber-bands it
    off an *un*modeled collider (e.g. a warp/teleporter trigger volume that carries
    no solid-collision file but still bounces you). Empty list when the geometry
    can't be solved (no collision data, no on-grid point fits).
    """
    try:
        from src.collision import CollisionWorld, get_collision_data
        from src.collision_math import find_safe_magic_grid_points
        from src import entity_collision

        origin = await client.body.position()
        zone_name = await client.zone_name()
        player_radius = await _resolve_player_radius(client, zone_name)
        collision_data = await get_collision_data(client, zone_name)
        world = CollisionWorld()
        world.load(collision_data)

        def _solve():
            extra_shapes = entity_collision.build_zone_static_shapes(zone_name, origin.z)
            return find_safe_magic_grid_points(
                world, origin, player_radius, factor,
                extra_shapes=extra_shapes, zone_name=zone_name, limit=limit,
            )

        grid_points, reason = await asyncio.to_thread(_solve)
        if grid_points:
            logger.debug(
                f"[magic_grid] {client.title}: {len(grid_points)} grid candidate(s) ({reason}); "
                f"nearest -> {grid_points[0]}"
            )
            return grid_points
        logger.debug(f"[magic_grid] {client.title}: no on-grid solution ({reason})")
    except Exception as e:
        logger.debug(f"[magic_grid] {client.title}: solve errored ({e!r})")
    return []


async def find_walkable_magic_point(client: Client, factor: float) -> XYZ | None:
    """Nearest walkable magic-grid point, or ``None``. Thin single-point wrapper over
    ``find_walkable_magic_points`` (prefer the plural form so an unmodeled warp volume
    can be skipped via verify-and-retry)."""
    points = await find_walkable_magic_points(client, factor, limit=1)
    return points[0] if points else None


def calc_chunks(points: list[XYZ], entity_distance: float = 3147.0) -> list[XYZ]:
    # Returns a list of center points of "chunks" of the map, as defined by the input points.
    min_pos = XYZ(0, 0, 0)
    max_pos = XYZ(0, 0, 0)

    # find the extremes, they act as corners
    for point in points:
        if point.x < min_pos.x:
            min_pos.x = point.x
        if point.y < min_pos.y:
            min_pos.y = point.x

        if point.x > max_pos.x:
            max_pos.x = point.x
        if point.y > max_pos.y:
            max_pos.y = point.y

    # we use an inscribed square for chunking so corners are correctly included, using circles makes dealing with them way more annnoying
    side_length = math.sqrt(2) * entity_distance
    half_side_length = side_length / 2

    # start half a side length into the base square
    min_pos.x += half_side_length
    min_pos.y += half_side_length
    max_pos.x -= half_side_length
    max_pos.y -= half_side_length

    def point_in_rect(top_left: XYZ, bottom_right: XYZ, point: XYZ) -> bool:
        return point.x >= top_left.x and point.x < bottom_right.x and point.y >= top_left.y and point.y < bottom_right.y

    # place the first square outside the area, it is adjusted at the start of the loop anyways
    current_point = XYZ(min_pos.x - side_length, min_pos.y, 0)
    chunk_points = []
    leftover_points = set(points)
    # Turning the given points into a grid would be more efficient than this algorithm
    while True:
        # move the center of the rectangle to next rectangle
        current_point.x += side_length
        if current_point.x - half_side_length > max_pos.x:
            # next row
            current_point.x = min_pos.x
            current_point.y += side_length
            if current_point.y - half_side_length > max_pos.y:
                # scanned until the end
                break

        # filter squares that do not contain any points
        square_top_left = XYZ(current_point.x - half_side_length, current_point.y - half_side_length, 0)
        square_bottom_right = XYZ(current_point.x + half_side_length, current_point.y + half_side_length, 0)
        contained_points = set([])
        for p in leftover_points:
            if point_in_rect(square_top_left, square_bottom_right, p):
                contained_points.add(p)
        # a point cannot be in multiple squares at once
        leftover_points = leftover_points - contained_points

        if len(contained_points) > 0:
            chunk_points.append(copy(current_point))

    print(f'chunks:{len(chunk_points)}')
    return chunk_points


def calculate_yaw(xyz_1: XYZ, xyz_2: XYZ) -> float:
    # Calculates the yaw between 2 points.
    dx = xyz_1.x - xyz_2.x
    dy = xyz_1.y - xyz_2.y

    return math.atan2(dx, dy)


def calculate_pitch(xyz_1: XYZ, xyz_2: XYZ) -> float:
    # Find the reference vector
    x = xyz_2.x - xyz_1.x
    y = xyz_2.y - xyz_1.y
    z = xyz_2.z - xyz_1.z

    return -math.atan2(z, math.sqrt(x ** 2 + y ** 2))
